// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bopunplxayuvcvrmsjhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvcHVucGx4YXl1dmN2cm1zamhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDkxMjMsImV4cCI6MjA2OTk4NTEyM30.HEr0Qof7yLa-x1n3FjUz4Hi5M9x4MfSSejBGju3A1CU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});